### ISSUE TITLE
组员自我介绍

### ISSUE THREAD

**Issue by alswl** [chenhao0327/so-relax#10]
队长不在，我开一个 Issue，大家互相认识一下。

*   叫我 3D 就好
*   AIWriter 的自我介绍：[欢迎你，新同学 | 长三角弃疾战队——与君和曲，共赏桃花水 · Issue #5 · AIWriter/Writer006](https://github.com/AIWriter/Writer006/issues/5#issuecomment-393588989)
*   擅长吃，喜欢喝茶，会写点代码。
*   常驻在上海，但是经常活动于杭州
*   对我感兴趣可以点击：[About - Log4D](https://blog.alswl.com/about/)

**Comment by ghost** [comment]
AIWriter 的自我介绍：回忆一个多月前，好像进步不大，总有点不堪回首的味道，当时写的自我介绍也甚是随意匆忙
https://github.com/AIWriter/Writer006/issues/4#issuecomment-393916399
目前在北京拷贝粘贴代码。
参加写作课的目标是培养自己的创作能力，感知能力，也是因为认同写作具有特殊意义这个观点而参加的。
做BP的目标是实践出真知。
星星教练说做BP最关键的是人，是有道理的，BP的对象是人，做BP的也是人。
和队长一起打出BP。

**Comment by chenhao0327** [comment]
大家好，我是陈浩，
*  Github：chenhao0327
* [AIWriter自我介绍](https://github.com/AIWriter/Writer006/issues/5)
* 目前在浙江绍兴嵊州市人民医院工作，是一名心血管医生。
* 你最擅长的一项技能：看病（特别是心血管内科的相关疾病）。
* 希望与收获：和大家共同完成一个满意的BP，更重要是遇到志同道合的伙伴。

**Comment by DoraDingzi** [comment]
大家好，我是钉子。
突然意识到我没有在开课帖子进行自我介绍，想到参加上海线下开学典礼，自我介绍的三个词：有趣、优秀同侪、自我认知。
* 擅长：故事。说不上擅长，做的是创意策划类工作，偶尔会有想法。
* 缘起：
巧合之下，我在听音乐「从前慢」，看到BP项目，联想到一个爱情故事。    
他承诺像车马慢的从前一样，一生只爱她一人，但却突发猝死了，女孩哭诉，他背弃了承诺。一生只爱一人，你的一生有多久呢？从现在，关注健康，为了守住承诺，为了爱的人。
