### ISSUE TITLE
BP主题讨论

### ISSUE THREAD

**Issue by chenhao0327** [chenhao0327/so-relax#2]
希望解决什么问题：呼吁大家重视自己的健康，尤其是亚健康人群。

具体从哪一个方面入手，欢迎大家各抒己见。

**Comment by chenhao0327** [comment]
我先抛砖引玉：
先从放慢工作生活节奏下手。每个人找到自己的节奏，不要和别人比较。

**Comment by alswl** [comment]
Issue 已经关掉了？

我觉得我还没有 Get 到特别详细的点。

*  这是主题是一个产品么？
*  产品形态什么样子？
*  给谁使用？
*  在什么场景下面使用?（比如有的产品是带小孩子读书，画画，教小孩编程）
