### ISSUE TITLE
BP产品呈现形式讨论

### ISSUE THREAD

**Issue by ghost** [chenhao0327/so-relax#8]
有了主题方向后，是先写故事还是确定呈现形式？呈现形式的可能要多搜些资料
- 公益实践活动；
- 体验馆形式，通过体验增强感受；
- 软件产品，APP辅助形式；
- 硬件产品，融入日常生活用品；
- ...其他形式

**Comment by alswl** [comment]
可以看看历史 BP 有哪些呈现方式，再评估一下我们能做到什么程度。

TODO

**Comment by chenhao0327** [comment]
[罗拉快跑](https://www.bilibili.com/video/av16451154?share_medium=android&share_source=weixin&bbid=19330F3B-887B-4441-9C72-351A86899FD314559infoc&ts=1532861767064)三次奔跑三次结果

[爱银发](http://www.aiyinfa.com/3)
